### ISSUE TITLE
Crash com.minttea.pmmobridge.events.BloodCompatEventHandler.awardSoulDrainXp

### ISSUE THREAD

**Issue by YoSiJo** [MintTeaTx/PMMOBridge#1]
Server crash from 
BloodMagic mod.

```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 1/21/21, 9:16 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.minttea.pmmobridge.events.BloodCompatEventHandler.awardSoulDrainXp(BloodCompatEventHandler.java:79) ~[pmmobridge:1.16.4-1.0.4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_7_BloodCompatEventHandler_awardSoulDrainXp_Syphon.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at wayoftime.bloodmagic.core.data.SoulNetwork.syphon(SoulNetwork.java:93) ~[bloodmagic:1.16.3-3.0.6-11] {re:classloading}
	at wayoftime.bloodmagic.core.data.SoulNetwork.syphon(SoulNetwork.java:87) ~[bloodmagic:1.16.3-3.0.6-11] {re:classloading}
	at wayoftime.bloodmagic.ritual.types.RitualLava.performRitual(RitualLava.java:257) ~[bloodmagic:1.16.3-3.0.6-11] {re:classloading}
	at wayoftime.bloodmagic.tile.TileMasterRitualStone.performRitual(TileMasterRitualStone.java:260) ~[bloodmagic:1.16.3-3.0.6-11] {re:classloading}
	at wayoftime.bloodmagic.tile.TileMasterRitualStone.onUpdate(TileMasterRitualStone.java:98) ~[bloodmagic:1.16.3-3.0.6-11] {re:classloading}
	at wayoftime.bloodmagic.tile.base.TileTicking.func_73660_a(TileTicking.java:28) ~[bloodmagic:1.16.3-3.0.6-11] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:1779) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:common.MixinWorld,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinServerWorld,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:834) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.minttea.pmmobridge.events.BloodCompatEventHandler.awardSoulDrainXp(BloodCompatEventHandler.java:79) ~[pmmobridge:1.16.4-1.0.4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_7_BloodCompatEventHandler_awardSoulDrainXp_Syphon.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at wayoftime.bloodmagic.core.data.SoulNetwork.syphon(SoulNetwork.java:93) ~[bloodmagic:1.16.3-3.0.6-11] {re:classloading}
	at wayoftime.bloodmagic.core.data.SoulNetwork.syphon(SoulNetwork.java:87) ~[bloodmagic:1.16.3-3.0.6-11] {re:classloading}
	at wayoftime.bloodmagic.ritual.types.RitualLava.performRitual(RitualLava.java:257) ~[bloodmagic:1.16.3-3.0.6-11] {re:classloading}
	at wayoftime.bloodmagic.tile.TileMasterRitualStone.performRitual(TileMasterRitualStone.java:260) ~[bloodmagic:1.16.3-3.0.6-11] {re:classloading}
	at wayoftime.bloodmagic.tile.TileMasterRitualStone.onUpdate(TileMasterRitualStone.java:98) ~[bloodmagic:1.16.3-3.0.6-11] {re:classloading}
	at wayoftime.bloodmagic.tile.base.TileTicking.func_73660_a(TileTicking.java:28) ~[bloodmagic:1.16.3-3.0.6-11] {re:classloading}
-- Block entity being ticked --
Details:
	Name: bloodmagic:masterritualstone // wayoftime.bloodmagic.tile.TileMasterRitualStone
	Block: Block{bloodmagic:masterritualstone}
	Block location: World: (154,64,56), Chunk: (at 10,4,8 in 9,3; contains blocks 144,0,48 to 159,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Block: Block{bloodmagic:masterritualstone}
	Block location: World: (154,64,56), Chunk: (at 10,4,8 in 9,3; contains blocks 144,0,48 to 159,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:1779) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:common.MixinWorld,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinServerWorld,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}


-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 2025
	Level dimension: minecraft:overworld
	Level spawn location: World: (208,70,128), Chunk: (at 0,4,0 in 13,8; contains blocks 208,0,128 to 223,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 5471191 game time, 6642137 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 67964 (now: false), thunder time: 140676 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:834) [?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (amd64) version 5.4.78-2-pve
	Java Version: 11.0.9.1, Debian
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Debian
	Memory: 12958945280 bytes (12358 MB) / 14143193088 bytes (13488 MB) up to 17825792000 bytes (17000 MB)
	CPUs: 4
	JVM Flags: 1 total; -Xmx17000M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/server.jar object_holder_definalize PLUGINSERVICE 
		/server.jar runtime_enum_extender PLUGINSERVICE 
		/server.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/server.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/server.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.37
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		pmmobridge-1.16.4-1.0.4.jar                       |PMMO Compatibility Mod        |pmmobridge                    |1.16.4-1.0.4        |DONE      |NOSIGNATURE
		Weeping-Angels-1.16.x-2.0.0.jar                   |Weeping Angels                |weeping_angels                |2.0.0               |DONE      |NOSIGNATURE
		platforms-1.16-1.7.8.jar                          |Platforms                     |platforms                     |1.7.8               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.0.62.jar                           |Just Enough Items             |jei                           |7.6.0.62            |DONE      |NOSIGNATURE
		Druidcraft-1.16.4-0.4.5.jar                       |Druidcraft                    |druidcraft                    |0.4.5               |DONE      |NOSIGNATURE
		Mekanism-1.16.4-10.0.18.445.jar                   |Mekanism                      |mekanism                      |10.0.18             |DONE      |NOSIGNATURE
		Undefeatables+1.1.jar                             |Undefeatables                 |undefeatables                 |1.1                 |DONE      |NOSIGNATURE
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |DONE      |NOSIGNATURE
		mgui-1.16.4-3.1.3.jar                             |mgui                          |mgui                          |3.1.3               |DONE      |NOSIGNATURE
		citadel-1.5.3.jar                                 |Citadel                       |citadel                       |1.5.3               |DONE      |NOSIGNATURE
		appliedenergistics2-8.2.0-beta.2.jar              |Applied Energistics 2         |appliedenergistics2           |8.2.0-beta.2        |DONE      |95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		TravelersBackpack-1.16.4-5.3.8.jar                |Traveler's Backpack           |travelersbackpack             |5.3.8               |DONE      |NOSIGNATURE
		decorative_blocks-1.16.4-1.7.2.jar                |Decorative Blocks             |decorative_blocks             |1.7.2               |DONE      |NOSIGNATURE
		engineerstools-1.16.4-1.1.2.jar                   |Engineer's Tools              |engineerstools                |1.1.2               |DONE      |bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		sophisticatedbackpacks-1.16.4-1.3.4.136.jar       |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.4-1.3.4.136    |DONE      |NOSIGNATURE
		Morpheus-1.16.4-4.2.68.jar                        |Morpheus                      |morpheus                      |4.2.68              |DONE      |NOSIGNATURE
		mahoutsukai-1.16.4-v1.27.4.jar                    |Mahou Tsukai                  |mahoutsukai                   |1.16.4-v1.27.4      |DONE      |NOSIGNATURE
		iceandfire-2.1.5-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.5-1.16.4        |DONE      |NOSIGNATURE
		MekanismGenerators-1.16.4-10.0.18.445.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.18             |DONE      |NOSIGNATURE
		immersive-portals-0.14-mc1.16.4-forge.jar         |Immersive Portals             |immersive_portals             |0.14                |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.37-universal.jar                |Forge                         |forge                         |35.1.37             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		shetiphiancore-1.16-3.8.4.jar                     |ShetiPhian-Core               |shetiphiancore                |3.8.4               |DONE      |NOSIGNATURE
		BloodMagic-1.16.3-3.0.6-11.jar                    |Blood Magic                   |bloodmagic                    |1.16.3-3.0.6-11     |DONE      |NOSIGNATURE
		structure_gel-1.16.4-1.7.4.jar                    |Structure Gel API             |structure_gel                 |1.7.4               |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.37-server.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		mcw-bridges-1.0.4-mc1.16.4.jar                    |Macaw's Bridges               |mcwbridges                    |1.0.4               |DONE      |NOSIGNATURE
		industrial-foregoing-1.16.4-3.2.8.2-6b5c95b.jar   |Industrial Foregoing          |industrialforegoing           |3.2.8.2             |DONE      |NOSIGNATURE
		torchmaster-2.3.6.jar                             |Torchmaster                   |torchmaster                   |2.3.6               |DONE      |NOSIGNATURE
		theoneprobe-1.16-3.0.6.jar                        |The One Probe                 |theoneprobe                   |1.16-3.0.6          |DONE      |NOSIGNATURE
		titanium-1.16.4-3.2.5.jar                         |Titanium                      |titanium                      |3.2.5               |DONE      |NOSIGNATURE
		ImmersiveEngineering-1.16.4-4.1.2-129.jar         |Immersive Engineering         |immersiveengineering          |1.16.4-4.1.2-129    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		MekanismAdditions-1.16.4-10.0.18.445.jar          |Mekanism: Additions           |mekanismadditions             |10.0.18             |DONE      |NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |DONE      |NOSIGNATURE
		dungeons_plus-1.16.4-1.1.1.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.1               |DONE      |NOSIGNATURE
		towers_of_the_wild-1.16.4-2.0.1.jar               |Towers Of The Wild            |towers_of_the_wild            |1.16.4-2.0.1        |DONE      |NOSIGNATURE
		curios-forge-1.16.4-4.0.3.5.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.5      |DONE      |NOSIGNATURE
		tetra-1.16.4-3.5.3.jar                            |Tetra                         |tetra                         |3.5.3               |DONE      |NOSIGNATURE
		Patchouli-1.16.4-48.jar                           |Patchouli                     |patchouli                     |1.16.4-48           |DONE      |NOSIGNATURE
		Mantle-1.16.4-1.6.52.jar                          |Mantle                        |mantle                        |1.6.52              |DONE      |NOSIGNATURE
		StorageDrawers-1.16.3-8.2.1.jar                   |Storage Drawers               |storagedrawers                |8.2.1               |DONE      |NOSIGNATURE
		performant-1.16.2-4-3.26m.jar                     |Performant                    |performant                    |3.26m               |DONE      |NOSIGNATURE
		Ceramics-1.16.4-1.6.0.jar                         |Ceramics                      |ceramics                      |1.6.0               |DONE      |NOSIGNATURE
		tombstone-1.16-6.2.5.jar                          |Corail Tombstone              |tombstone                     |1.16-6.2.5          |DONE      |NOSIGNATURE
		structurize-0.13.100-RELEASE-universal.jar        |Structurize                   |structurize                   |0.13.100-RELEASE    |DONE      |NOSIGNATURE
		minecolonies-0.13.480-BETA-universal.jar          |Minecolonies                  |minecolonies                  |0.13.480-BETA       |DONE      |NOSIGNATURE
		MekanismTools-1.16.4-10.0.18.445.jar              |Mekanism: Tools               |mekanismtools                 |10.0.18             |DONE      |NOSIGNATURE
		majruszs-difficulty-1.16.4-0.3.1.jar              |Majrusz's Progressive Difficul|majruszs_difficulty           |0.3.1               |DONE      |NOSIGNATURE
		Project_MMO-1.16.4-3.40.1.jar                     |Project MMO                   |pmmo                          |1.16.4-3.40.1       |DONE      |NOSIGNATURE
		engineersdecor-1.16.4-1.1.6.jar                   |Engineer's Decor              |engineersdecor                |1.1.6               |DONE      |bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		cc-tweaked-1.16.4-1.95.2.jar                      |CC: Tweaked                   |computercraft                 |1.95.2              |DONE      |NOSIGNATURE
		occultism-1.0.4.jar                               |Occultism                     |occultism                     |1.0.4               |DONE      |NOSIGNATURE
		moreoverlays-1.18.11-mc1.16.4.jar                 |More Overlays Updated         |moreoverlays                  |1.18.11-mc1.16.4    |DONE      |NOSIGNATURE
		switchbow-1.7.jar                                 |Switch-Bow                    |switchbow                     |1.7                 |DONE      |NOSIGNATURE
		forge-1.16.4-geckolib-3.0.0.jar                   |GeckoLib                      |geckolib3                     |3.0.0               |DONE      |NOSIGNATURE
		ars_nouveau-1.16.4-1.11.1.jar                     |Ars Nouveau                   |ars_nouveau                   |1.11.1              |DONE      |NOSIGNATURE
	Crash Report UUID: 3f3fbc6f-c9ec-436e-8e1e-dae708fc07ac
	Player Count: 0 / 20; []
	Data Packs: vanilla, mod:pmmobridge, mod:weeping_angels (incompatible), mod:platforms, mod:jei, mod:druidcraft (incompatible), mod:mekanism, mod:undefeatables, mod:create (incompatible), mod:mgui (incompatible), mod:citadel (incompatible), mod:appliedenergistics2 (incompatible), mod:travelersbackpack (incompatible), mod:decorative_blocks, mod:engineerstools, mod:sophisticatedbackpacks, mod:morpheus (incompatible), mod:mahoutsukai (incompatible), mod:iceandfire (incompatible), mod:mekanismgenerators, mod:immersive_portals (incompatible), mod:forge, mod:shetiphiancore, mod:bloodmagic, mod:structure_gel, mod:mcwbridges (incompatible), mod:industrialforegoing (incompatible), mod:torchmaster (incompatible), mod:theoneprobe, mod:titanium (incompatible), mod:immersiveengineering (incompatible), mod:mekanismadditions, mod:valhelsia_structures (incompatible), mod:dungeons_plus, mod:towers_of_the_wild, mod:curios, mod:tetra, mod:patchouli (incompatible), mod:mantle (incompatible), mod:storagedrawers (incompatible), mod:performant (incompatible), mod:ceramics (incompatible), mod:tombstone, mod:structurize, mod:minecolonies (incompatible), mod:mekanismtools, mod:majruszs_difficulty, mod:pmmo (incompatible), mod:engineersdecor, mod:computercraft, mod:occultism, mod:switchbow, mod:geckolib3 (incompatible), mod:ars_nouveau, mod:moreoverlays
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by starluneaux** [comment]
I'll look into this one, so sorry for the late reply!

**Comment by starluneaux** [comment]
What it looks like after some investigation, the entity itself was corrupted and raised an NPE from the master ritual stone, you can open forge.cfg and scroll down until you find the settings removeErroringEntities and removeErroringTileEntities.  Set those to true and you should be fine.
