### ISSUE TITLE
[Crash] Latest 1.16.5 Version causes world loading error

### ISSUE THREAD

**Issue by Bossos11** [MintTeaTx/PMMOBridge#3]
The newest version of the mod in combination with Ars Noveau causes a world loading error:

Preparing crash report with UUID 8618a573-d13e-4230-95e9-c229b4f5ca6c
10:35:58.618
net.minecraft.server.MinecraftServer
Server thread
Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking player
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:137)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$13865/301606258.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: com.hollingsworth.arsnouveau.api.event.ManaRegenCalcEvent.setRegen(I)V
	at com.minttea.pmmobridge.events.ArsCompatEventHandler.manaRegenByLevel(ArsCompatEventHandler.java:69)
	at net.minecraftforge.eventbus.ASMEventHandler_8_ArsCompatEventHandler_manaRegenByLevel_ManaRegenCalcEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2531/1287647842.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at com.hollingsworth.arsnouveau.api.util.ManaUtil.getManaRegen(ManaUtil.java:104)
	at com.hollingsworth.arsnouveau.common.event.ManaCapEvents.playerOnTick(ManaCapEvents.java:32)
	at net.minecraftforge.eventbus.ASMEventHandler_600_ManaCapEvents_playerOnTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2531/1287647842.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:85)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:196)
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404)
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	... 7 more

**Comment by AngellusMortis** [comment]
Dupe of #2

**Comment by XxInvictus** [comment]
It's been a long time coming but I have just uploaded a new version to curseforge which should fix this bug:
https://www.curseforge.com/minecraft/mc-mods/pmmo-bridge/files/3640552
