### ISSUE TITLE
[Crash] Latest 1.16.5 Ars Nauveau build, caused by mana regen calc event

### ISSUE THREAD

**Issue by ShadowWolfBR** [MintTeaTx/PMMOBridge#5]
[Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: com.hollingsworth.arsnouveau.api.event.ManaRegenCalcEvent.setRegen(I)V
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class com.minttea.pmmobridge.events.ArsCompatEventHandler manaRegenByLevel(Lcom/hollingsworth/arsnouveau/api/event/ManaRegenCalcEvent;)V
		2: ASM: class com.hollingsworth.arsnouveau.common.event.ArsEvents regenCalc(Lcom/hollingsworth/arsnouveau/api/event/ManaRegenCalcEvent;)V
java.lang.NoSuchMethodError: com.hollingsworth.arsnouveau.api.event.ManaRegenCalcEvent.setRegen(I)V
	at com.minttea.pmmobridge.events.ArsCompatEventHandler.manaRegenByLevel(ArsCompatEventHandler.java:69)
	at net.minecraftforge.eventbus.ASMEventHandler_3_ArsCompatEventHandler_manaRegenByLevel_ManaRegenCalcEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at com.hollingsworth.arsnouveau.api.util.ManaUtil.getManaRegen(ManaUtil.java:104)
	at com.hollingsworth.arsnouveau.common.event.ManaCapEvents.playerOnTick(ManaCapEvents.java:32)
	at net.minecraftforge.eventbus.ASMEventHandler_679_ManaCapEvents_playerOnTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:85)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:196)
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404)
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.lang.Thread.run(Unknown Source)

**Comment by ShadowWolfBR** [comment]
Just a edit, the crash happens after you enter inside a world (new and old both)

 I'm using FerriteCore, Performant and RandomTweaks.

**Comment by ClayPigeon** [comment]
Replicated.
Log: https://gist.github.com/ClayPigeon/b1b0e2a9a40c4f41666e1c9d214773e2

Also tested with Ars 1.18.3, 1.18, 1.17, 1.16.2, 1.16.1, and 1.16. Also tested with newer versions of Geckolib.

**Comment by XxInvictus** [comment]
This appears to be a duplicate of #2

**Comment by XxInvictus** [comment]
It's been a long time coming but I have just uploaded a new version to curseforge which should fix this bug:
https://www.curseforge.com/minecraft/mc-mods/pmmo-bridge/files/3640552
